<a href="https://colab.research.google.com/github/diegoalonsosm/Apuntes_CC3001/blob/main/EjercicioSemana2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Ejercicio 1.2 (Diego Alonso Sánchez Manríquez)**

**Entregado por Diego Alonso Sánchez Manríquez** \\
**Curso Algoritmos y Estructuras de Datos (CC3001)**

*Existe un algoritmo alternativo a Hoare, que resulta en una codificación más 
sencilla. Este algoritmo, debido a Lomuto, se basa en el siguiente invariante:*

*En este algoritmo, en cada iteración, si  a[j]<p , se intercambian  a[i]  con a[j]  y se incrementa  i , porque ahora hay un elemento más en el grupo de los menores que  p . Después de esto, se incrementa  j , incondicionalmente 
(¿por qué es correcto hacer eso?).*

*Programe la partición de Lomuto en el recuadro siguiente y pruébela.* \\

In [14]:
# particionLomuto: list int -> tuple
# Entrega una tupla ( p = punto de corte, i = elementos <p, a = lista particionada )
# Ej: assert particionLomuto(A,100) -> ([73,21,34,98,56,37,77,65,82,15,36],100,[]) 
# Ej: particionLomuto(A,50) -> (50,5,[21,34,37,15,36,73,77,65,82,98,56])

def particionLomuto(a,p):
    
    # Se ejecuta hasta que no hayan elementos desconocidos, es decir, 
    # hasta que se haya identificado la relación de orden que tiene p
    # con cada uno de los elemento de la lista
    
    # Asignación de variables
    n=len(a); i=0; j=0
    
    while j<=n-1: # Condición: quedan elementos desconocidos
    
        if a[j]<p:
            (a[i],a[j])=(a[j],a[i]) # Se intercambian los elementos en i y j
            i+=1
        j+=1

    return (p,i,a)

# Lista para ser particionada
A = [73,21,34,98,56,37,77,65,82,15,36]

particionLomuto(A,50)

# Pruebas
assert particionLomuto(A,50) == (50,5,[21,34,37,15,36,73,77,65,82,98,56])
assert particionLomuto(A,100) == (100,11,[21,34,37,15,36,73,77,65,82,98,56])

Se incluye una función *test()* basada en *verifica_particion()* que hace *n* particiones aleatorias y las imprime en pantalla.


In [16]:
import numpy as np

intervaloNumeros = 200 # Indicar intervalo máximo
numeroArreglo = 10 # Indicar número del arreglo 

def test(n):
    
    p = np.random.randint(0,intervaloNumeros,numeroArreglo) # Arreglo de número aleatorios
    
    # Entregada en tarea, originalmente, definida como verifica_particion()
    def verificador(t):
        (p,m,a)=t
        print(a[0:m],p,a[m:])
        print("Partición OK" if (m==0 or max(a[0:m])<p) and (m==len(a) or min(a[m:])>p)
          else "Error")
    
    print() # Ignorar (legibilidad en consola)
    
    for i in range(1,n):
        
        alAzar = np.random.randint(1,200) # Genera un [p] aleatorio
        
        if alAzar in p: # Genera otro [p] si este ya está en [a]
            while alAzar in p:
                alAzar = np.random.randint(1,200)
                
        verificador(particionLomuto(p,alAzar))
        print() # Ignorar (legibilidad en consola)

test(20) # Se imprimen 20 pruebas


[  0 124  23 140 111  16 185 146   6   8] 191 []
Partición OK

[ 0 23 16  6  8] 68 [124 185 146 140 111]
Partición OK

[  0  23  16   6   8 124 111] 130 [146 140 185]
Partición OK

[0] 2 [ 23  16   6   8 124 111 146 140 185]
Partición OK

[  0  23  16   6   8 124 111 146 140] 172 [185]
Partición OK

[ 0 23 16  6  8] 68 [124 111 146 140 185]
Partición OK

[  0  23  16   6   8 124 111] 131 [146 140 185]
Partición OK

[ 0 23 16  6  8] 32 [124 111 146 140 185]
Partición OK

[  0  23  16   6   8 124 111 146 140] 161 [185]
Partición OK

[ 0 23 16  6  8] 70 [124 111 146 140 185]
Partición OK

[  0  23  16   6   8 124 111 146 140] 166 [185]
Partición OK

[  0  23  16   6   8 111] 116 [124 146 140 185]
Partición OK

[  0  23  16   6   8 111 124] 137 [146 140 185]
Partición OK

[  0  23  16   6   8 111 124 146 140] 155 [185]
Partición OK

[ 0 16  6  8] 20 [ 23 111 124 146 140 185]
Partición OK

[  0  16   6   8  23 111 124 140] 145 [146 185]
Partición OK

[  0  16   6   8  23 111 124 140 146] 1